version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examinpi
      MYSQL_USER: root  
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
   

  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8089:8089" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/examinpi?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root  
    
